general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
    ignore_dbus_inhibit = false
}

# Dim screen 20 seconds before blank
listener {
    timeout = 80
    on-timeout = brightnessctl -s set 10          # Dim backlight (OLED friendly)
    on-resume = brightnessctl -r                  # Restore backlight
}

listener {
    timeout = 100
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 120
    on-timeout = loginctl lock-session
}

listener {
    timeout = 300
    on-timeout = systemctl suspend
}
